version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PIDFILE=/usr/src/app/tmp/pids/server.pid
      - RAILS_ENV=development
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development
      - DATABASE_HOST=database.service.ecosystem.internal
      - REDIS_URL=redis://redis.service.ecosystem.internal
    networks:
      - internal
    depends_on:
      - database.service.ecosystem.internal
      - redis.service.ecosystem.internal

  database.service.ecosystem.internal:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=development

  redis.service.ecosystem.internal:
    image: redis:4.0-alpine
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
