name: Rails
on: push

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: ecosystem
          DATABASE_NAME: ecosystem_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v4
      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 15
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
          cache-version: 1

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_NAME: ecosystem_test
          POSTGRES_USER: ecosystem
          POSTGRES_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
        run: bundle exec rake db:create db:migrate test